# Generated by Django 5.1.7 on 2025-05-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='slug',
        ),
    ]
